theme = "hyde"
baseURL = "https://underthehood.jacquietran.com/"
languageCode = "en-GB"
title = "Under The Hood"
googleAnalytics = "UA-23505591-3"
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  # Colour theme for site
  themeColor = "theme-base-jt"
  # Sets the meta tag description
  description = "Dive into the processes and practices that underpin sports analytics. A blog by Jacquie Tran."
  author      = "Jacquie Tran"
  dateFormat	= "Mon Jan 2 2006"
  
[params.intro]
  header    = "Under The Hood"
  paragraph = "Dive into the processes and practices that underpin sports analytics. A blog by Jacquie Tran."
  
# Sets the menu items in the navigation bar
# Identifier prepends a Font Awesome icon to the menu item

[[menu.main]]
  name = "Topics"
  url = "/categories/"
  identifier = "fa fa-sitemap"
  weight = 3