theme = "hugo-theme-minos"
baseURL = "https://underthehood.jacquietran.com/"
languageCode = "en"
title = "Under The Hood"
paginate = 10
googleAnalytics = "UA-123-45"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    # smartToc = false
    
[menu]

    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
    [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
    
    [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3
    
    [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4