---
title: Text mining of Wimbledon tweets using rtweet and tidytext
author: Jacquie Tran
date: '2018-07-20'
slug: text-mining-of-wimbledon-tweets-using-rtweet-and-tidytext
categories:
  - Off-field analyses
tags:
  - text mining
  - tennis
  - sports analytics
  - r stats
  - tidytext
  - rtweet
draft: yes
---

# New job, new skills
This year, I started in a new role as Senior Insights Researcher at High Performance Sport New Zealand. For me, one of the big drawcards of this role was the opportunity to learn and grow my skills and competencies as a performance sport professional.

Our team regularly deals with qualitative data, so as an applied sport scientist with a strongly quantitative training, it has been a steep learning curve but also enjoyable to open my mind up to different ways of thinking and knowing.

Of what I have learned so far, the intersection of my old skills and new skills could be simply represented as: statistical programming + text data = text mining.

Online discussions about sports analytics seem heavily focused on numbers and what we can do with quantitative data. I remain just as interested in these discussions as I was before starting my current job, but I also see opportunities for more of us in the sports analytics community to think about what else we can learn by capturing and analysing qualitative data. In that spirit, this post is a brief glimpse at what is possible when applying text mining methods.

# Getting the data

I've been thinking about writing this post for a couple of months now, and every so often I trawl the internet looking for text corpuses that are relevant to sport - so far, my efforts have turned up fairly light results. (If anyone knowledgeable in this domain can point me to relevant open data sets, then [please get in touch!]())

- Introduce `rtweet` package, point to tutorial(s)
- Outline features / constraints of the data extraction (lang = en, conversion of list-columns tibble to flat data frame for exporting to CSV)
- Point to Github repo
- Import the CSVs
- Data dictionary

# Cleaning the data

- Introduce `tidytext` package, point to book and tutorial(s)
- Fix text encoding if needed
- Remove stop words
- Note duplicate tweets

# n-gram frequency


# Sentiment analysis

- bing (positive / negative binary categorisation)
- AFINN (positive to negative, continuous scale)
- nrc (multiple sentiment categories)

# What else can text mining do?
- Sentiment analysis at the sentence level
- n-gram network analysis
- Parts-of-speech tagging
- Topic modelling