---
title: Giving back to sport science
author: Jacquie Tran
date: '2020-04-13'
slug: giving-back-to-sport-science
categories:
  - General ramblings
tags:
  - r stats
  - sport science
  - sports analytics
draft: yes
---

There's no doubt that we, globally, are going through tough times as the COVID-19 pandemic sweeps through many countries. Every aspect of life has been affected, and this includes sport.

While I live in NZ (and am *so* grateful to be here, now more than ever), I've been keeping a close eye on the news from back home in Australia and elsewhere around the world. Friends and colleagues throughout sport have been heavily impacted - many having been stood down without pay or made redundant altogether.

In these times, I want to give back to the sport science community. So I posted this call-out on Twitter recently:

<center><blockquote class="twitter-tweet"><p lang="en" dir="ltr">Sport science friends interested in learning R:<br><br>I want to give back to our community which is going through a super tough time. Thinking of preparing <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> tutorials, webinars, screencasts...<br><br>What topics would be useful to cover? RTs welcome 😊<a href="https://twitter.com/Benita_Lalor?ref_src=twsrc%5Etfw">@Benita_Lalor</a> <a href="https://twitter.com/alicesweeting?ref_src=twsrc%5Etfw">@alicesweeting</a></p>&mdash; Jacquie Tran (@jacquietran) <a href="https://twitter.com/jacquietran/status/1247445854610313216?ref_src=twsrc%5Etfw">April 7, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></center>

Lots of people pitched in with great suggestions - thank you! - so the list below reflects key topic areas mentioned by those who tweeted me back :)

- "The basics"
- Cleaning data and using the tidyverse
- Visualising data
- Learning R as an Excel / SPSS user
- Web scraping and working with APIs
- Working with sports data
- Statistical analysis using R
- Using code-generated slide decks